[package]
name = "quinn-proto"
version = "0.4.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "State machine for the QUIC transport protocol"
keywords = ["quic"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
maintenance = { status = "experimental" }

[features]
default = ["tls-rustls"]
tls-rustls = ["rustls", "webpki", "ring"]

[dependencies]
bytes = "0.4.7"
err-derive = "0.2"
fnv = "1.0.6"
lazy_static = "1"
rand = "0.7"
ring = { version = "0.16.7", optional = true }
rustls = { version = "0.16", features = ["quic"], optional = true }
slab = "0.4"
webpki = { version = "0.21", optional = true }
slog = { version = "2.5", features = ["max_level_trace"] } # For debugging

[dev-dependencies]
assert_matches = "1.1"
hex-literal = "0.2.0"
rcgen = "0.7"
slog = { version = "2.5", features = ["max_level_trace"] } # For debugging
