[package]
name = "quinn-h3"
version = "0.0.1"
authors = [
    "Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>",
    "Jean-Christophe BEGUE <begue.jc@gmail.com>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "QUIC HTTP/3 protocol implementation"
readme = "../README.md"
keywords = ["quic", "http3", "qpack"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
codecov = { repository = "djc/quinn" }
maintenance = { status = "experimental" }
travis-ci = { repository = "djc/quinn" }

[dependencies]
bitlab = "0.8.1"
bytes = "0.4.7"
err-derive = "0.2"
futures = { package = "futures-preview", version = "0.3.0-alpha.18" }
http = { git = "https://github.com/hyperium/http/", rev = "912534f1ef27d8a9050a4bd40d5ea0ee35136ea7" }
lazy_static = "1"
quinn-proto = { path = "../quinn-proto", version = "0.4.0" }
quinn = { path = "../quinn", version = "0.4.0" }
# slog = { version = "2.1", features = ["max_level_trace", "release_max_level_warn"]}
#slog = {version = "2.5", features = ["max_level_trace", "release_max_level_warn"] }
slog = { version = "2.1" }
string = "0.2"
tokio = "0.2.0-alpha.5"
tokio-io = "0.2.0-alpha.5"
tokio-codec = "0.2.0-alpha.5"

[dev-dependencies]
assert_matches = "1.1"
directories = "2.0.1"
failure = "0.1"
proptest = "0.9.1"
rand = "0.7.0"
rcgen = "0.7"
slog-term = "2"
structopt = "0.3.0"
url = "2"

[[example]]
name = "h3"

# [[example]]
# name = "simple_server"

# [[example]]
# name = "simple_client"
